local opt = vim.opt

opt.tabstop       = 2
opt.cmdheight     = 0
opt.laststatus    = 0
opt.shiftwidth    = 2
opt.showtabline   = 2
opt.conceallevel  = 3
opt.mouse         = ""
opt.winwidth      = 10
opt.textwidth     = 80
opt.winminwidth   = 10
opt.scrolloff     = 999
opt.updatetime    = 200
opt.timeoutlen    = 500
opt.wrap          = true
opt.number        = true
opt.timeout       = true
opt.confirm       = true
opt.undofile      = true
opt.expandtab     = true
opt.smartcase     = true
opt.autowrite     = true
opt.cursorline    = true
opt.splitright    = true
opt.splitbelow    = true
opt.ignorecase    = true
opt.shiftround    = true
opt.autoindent    = true
opt.breakindent   = true
opt.termguicolors = true
opt.list          = false
opt.cindent       = false
opt.smarttab      = false
opt.hlsearch      = false
opt.showmode      = false
opt.swapfile      = false
opt.smartindent   = false
opt.equalalways   = false
opt.virtualedit   = "block"
opt.splitkeep     = "screen"
opt.signcolumn    = "number"
opt.formatoptions = "cjlnoqrt"
opt.clipboard     = "unnamedplus"
opt.grepprg       = "rg --vimgrep"
opt.fillchars     = { eob = " " }
opt.completeopt   = { "menu", "menuone", "noselect", "noinsert", }
opt.shortmess:append("I")
